### ISSUE TITLE
error at node devServer.js

### ISSUE THREAD

**Issue by Blak3Nick** [wesbos/Learn-Redux-Starter-Files#10]
Error: listen EADDRINUSE 127.0.0.1:7770
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:84:10)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! learn-redux@1.0.0 start: `node devServer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the learn-redux@1.0.0 start script 'node devServer.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the learn-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node devServer.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs learn-redux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls learn-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\wes-bos\Learn-Redux-Starter-Files\learn-redux\npm-debug.log

[npm-debug.txt](https://github.com/wesbos/Learn-Redux-Starter-Files/files/293284/npm-debug.txt)

**Comment by rublev** [comment]
Looks like local port 7770 is already in use. I'd check to see what you have running on that port. Type `netstat` into terminal and look for something using port 7770.

**Comment by Blak3Nick** [comment]
@rublev 
That was it exactly. I killed the process and I am back up and running. Thank you so much. Sorry for the simple error. I am still getting used to these types of programs.

**Comment by rublev** [comment]
Great!
