### ISSUE TITLE
Production Build, not building.

### ISSUE THREAD

**Issue by TheoMer** [wesbos/Learn-Redux-Starter-Files#21]
Running `npm build` does not output anything, and I'm keen to test deploy to firebase. 

What am I missing here?

**Comment by TheoMer** [comment]
@wesbos I'm receiving the following error after running `npm run build':

`> learn-redux@1.0.0 build C:\Users\Theo\Documents\Visual Studio 2015\Projects\Learn-Redux-Starter-Files\learn-redux`
`> npm run clean && npm run build:webpack`


`> learn-redux@1.0.0 clean C:\Users\Theo\Documents\Visual Studio 2015\Projects\Learn-Redux-Starter-Files\learn-redux`
`> rimraf dist`


`> learn-redux@1.0.0 build:webpack C:\Users\Theo\Documents\Visual Studio 2015\Projects\Learn-Redux-Starter-Files\learn-redux`
`> NODE_ENV=production webpack --config webpack.config.prod.js`

`'NODE_ENV' is not recognized as an internal or external command,`
`operable program or batch file.`

**Comment by TheoMer** [comment]
My system details are as follows:

OS: Windows 10 Pro
NPM: 3.9.5
Node: 6.2.2

**Comment by wesbos** [comment]
Hey - Set your NODE_ENV variable - http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows
