### ISSUE TITLE
What's the "`" is doing in Lesson 13 Photo file?

### ISSUE THREAD

**Issue by maximveksler** [wesbos/Learn-Redux-Starter-Files#9]
Look at this code ```<Link to={`/view/${post.code}`}>``` copied from https://github.com/wesbos/Learn-Redux-Starter-Files/blob/master/13/components/Photo.js#L11 what does the ``` ` ``` does?

**Comment by rublev** [comment]
ES2015 template literals.

**Comment by maximveksler** [comment]
So say post.code = abcfoobar
So this translate to `<Link to={'/view/abcfoobar'}>` ? 

Could be useful to drop a word about that in one of the lessons.

**Comment by rublev** [comment]
Yes, and I don't think so as this course is not responsible for covering the entirety of ES2015 which itself would be an entire web series.

**Comment by maximveksler** [comment]
Naaaaa, we wouldn't. He did explained about the spread operator. Could have shared a work for at least the name of this feature. I tried to look for "react-router tilde to". Obviously that gave me nothing.

--
puıɯ ʎɯ ɯoɹɟ ʇuǝs

**Comment by rublev** [comment]
Yeah I feel your pain, I've been messing with all this stuff for the past month.

**Comment by wesbos** [comment]
Yeah sorry I assume some ES6 Knowledge in this course. But never fear, I bet you will like my next course ;) ;)
